# Generated by Django 3.1.3 on 2024-09-07 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_auto_20240905_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
        migrations.AddField(
            model_name='question',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='image1/', verbose_name='업로드 이미지1'),
        ),
        migrations.AddField(
            model_name='question',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='image2/', verbose_name='업로드 이미지2'),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(),
        ),
    ]
