# Generated by Django 3.1.3 on 2024-09-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_auto_20240907_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_image',
            field=models.ImageField(blank=True, null=True, upload_to='answer_image/', verbose_name='업로드 이미지'),
        ),
    ]
